spring:
  application:
    name: demo_a
  shardingsphere:
    mode:
      type: Memory # 集群元数据使用内存存储
    props:
      # 打印sql
      sql-show: true
    datasource:
      # 这个集群的节点名称（自定义）
      names: master,slave01,slave02
      master: # 节点名称对应的数据库配置
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.120.161:3006/business_a?allowPublicKeyRetrieval=true
        username: root
        password: 123456
      slave01:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.120.161:3005/business_a?allowPublicKeyRetrieval=true
        username: root
        password: 123456
      slave02:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.120.161:3007/business_a?allowPublicKeyRetrieval=true
        username: root
        password: 123456
  profiles:
#    active: rw # 测试读写分离
    active: row # 测试水平分表